global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['psiem_prometheus:9090']
    metrics_path: '/prometheus/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['psiem_node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['psiem_cadvisor:8080']
