version = 5.1.0
archive_dir = /etc/letsencrypt/archive/myaegis.org
cert = /etc/letsencrypt/live/myaegis.org/cert.pem
privkey = /etc/letsencrypt/live/myaegis.org/privkey.pem
chain = /etc/letsencrypt/live/myaegis.org/chain.pem
fullchain = /etc/letsencrypt/live/myaegis.org/fullchain.pem
[renewalparams]
account = f7c0d6aea9173bb632160d2d83ebf10a
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
myaegis.org = /var/www/certbot
www.myaegis.org = /var/www/certbot
